WebProgramlamaProje.MVC/Areas/Admin/Controllers/BrandController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProgramlamaProje.Business.Abstract;
using WebProgramlamaProje.Entities;
using WebProgramlamaProje.MVC.Infrastructure;

namespace WebProgramlamaProje.MVC.Areas.Admin.Controllers
{
	[CustomAuthenticationFilter]
	[CustomAuthorize("Admin")]
	public class BrandController : Controller
	{
		private readonly IBrandService _brandService;

		public BrandController(IBrandService brandService)
		{
			_brandService = brandService;
		}

		// GET: Admin/Brand
		public ActionResult Index()
		{
			var brands = _brandService.GetAllBrands();
			return View(brands);
		}

		[HttpGet]
		public ActionResult Add()
		{
			return View();
		}

		[HttpPost]
		public ActionResult Add(Brand model)
		{
			if (ModelState.IsValid)
			{
				_brandService.AddOneBrand(model);
				return RedirectToAction("Index");
			}
			return View();
		}

		public ActionResult Remove(int id)
		{
			_brandService.RemoveOneBrand(id);

			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Update(int id)
		{
			var model = _brandService.GetBrandById(id);
			return View(model);
		}

		[HttpPost]
		public ActionResult Update(Brand model)
		{
			if (ModelState.IsValid)
			{
				_brandService.UpdateOneBrand(model);

				return RedirectToAction("Index");
			}
			return View();
		}
	}
}

WebProgramlamaProje.MVC/Areas/Admin/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using WebProgramlamaProje.Business.Abstract;
using WebProgramlamaProje.Business.Concrete;
using WebProgramlamaProje.DataAccess.Concrete;
using WebProgramlamaProje.MVC.Areas.Admin.Models;
using WebProgramlamaProje.MVC.Infrastructure;

namespace WebProgramlamaProje.MVC.Areas.Admin.Controllers
{
	[CustomAuthenticationFilter]
	[CustomAuthorize("Admin")]
	public class UserController : Controller
	{
		private readonly IUserService _userManager;
		private readonly IRoleService _roleService;

		public UserController(IUserService userManager, IRoleService roleService)
		{
			_userManager = userManager;
			_roleService = roleService;
		}

		// GET: Admin/User
		public ActionResult Index()
		{
			var users = _userManager.GetAllUsersWithDetails();
			return View(users);
		}

		[HttpGet]
		public ActionResult Add()
		{
			var model = new UserInsertionViewModel();
			model.RoleList = GetRoleList();

			return View(model);
		}

		[HttpPost]
		public ActionResult Add(UserInsertionViewModel model)
		{
			if (ModelState.IsValid)
			{
				var isMeailExist = _userManager.IsUserMailExist(model.User.Email);
				if (!isMeailExist)
				{
					model.User.DateOfRegistration = DateTime.Now;

					_userManager.AddUser(model.User);
					return RedirectToAction("Index");
				}
				ModelState.AddModelError("", "Bu eposta başka bir kullanıcı tarafından kullanılıyor. Lütfen başka bir eposta seçin.");
			}

			model.RoleList = GetRoleList();
			return View(model);
		}

		public ActionResult Remove(int id)
		{
			_userManager.RemoveUser(id);
			return RedirectToAction("Index");
		}

		[HttpGet]
		public ActionResult Update(int id)
		{
			var model = new UserInsertionViewModel();
			var user = _userManager.GetUserWithDetailsById(id);
			model.User = user;
			model.RoleList = GetRoleList();
			return View(model);
		}

		[HttpPost]
		public ActionResult Update(UserInsertionViewModel model)
		{
			if (ModelState.IsValid)
			{
				_userManager.UpdateUser(model.User);
				return RedirectToAction("Index");
			}
			model.RoleList = GetRoleList();
			return View(model);
		}

		private List<SelectListItem> GetRoleList()
		{
			var list = new List<SelectListItem>();
			var roles = _roleService.GetAllRoles();

			foreach (var r in roles)
			{
				list.Add(new SelectListItem { Text = r.Name, Value = r.Id.ToString() });
			}

			return list;
		}
	}
}

WebProgramlamaProje.MVC/Controllers/CategoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProgramlamaProje.Business.Abstract;

namespace WebProgramlamaProje.MVC.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;

		public CategoryController(ICategoryService categoryService)
		{
			_categoryService = categoryService;
		}

		// GET: Category
		public ActionResult Index()
        {
            var model = _categoryService.GetAllCategories();
            return View(model);
        }
    }
}

WebProgramlamaProje.MVC/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebProgramlamaProje.Business.Abstract;
using WebProgramlamaProje.MVC.Models;

namespace WebProgramlamaProje.MVC.Controllers
{
	public class ProductController : Controller
	{
		private readonly IProductService _productService;
		private readonly IBrandService _brandService;
		private readonly ICategoryService _categoryService;

		public ProductController(IProductService productService, ICategoryService categoryService, IBrandService brandService)
		{
			_productService = productService;
			_categoryService = categoryService;
			_brandService = brandService;
		}

		// GET: Product
		public ActionResult Index(string searchTerm = null, int categoryId = 0, int brandId = 0)
		{
			var model = new ProductMenuViewModel();
			model.Products = _productService.GetAllProductWithDetails(searchTerm, categoryId, brandId);
			model.Brands = _brandService.GetAllBrands();
			model.Categories = _categoryService.GetAllCategories();
			return View(model);
		}

		public ActionResult Details(int id)
		{
			var product = _productService.GetProductWithDetailsById(id);

			return View(product);
		}
	}
}

WebProgramlamaProje.MVC/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
</head>
<body>

    @{Html.RenderPartial("_Navbar");}

    <main class="container">
        @RenderBody()
    </main>

    @{Html.RenderPartial("_Footer");}


    <script language="javascript" src="~/Scripts/bootstrap.bundle.min.js"></script>
</body>
</html>

WebProgramlamaProje.MVC/Areas/Admin/Views/Shared/_Navbar.cshtml
<nav class="navbar navbar-expand-lg bg-dark border-bottom border-body" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="@Url.Action("Index","Dashboard")">Admin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    @Html.ActionLink("Kullanıcılar", "Index", "User", new { area = "Admin" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Ürünler", "Index", "Product", new { area = "Admin" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Kategoriler", "Index", "Category", new { area = "Admin" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Markalar", "Index", "Brand", new { area = "Admin" }, new { @class = "nav-link" })
                </li>
                <li class="nav-item">
                    @Html.ActionLink("Siparişler", "Index", "Order", new { area = "Admin" }, new { @class = "nav-link" })
                </li>
            </ul>
            <a class="btn btn-outline-light mx-1" href="/">Mağaza</a>
            <a class="btn btn-outline-light mx-1">Çıkış yap</a>
        </div>
    </div>
</nav>